### ISSUE TITLE
LVL Sound

### ISSUE THREAD

**Issue by Ben1138** [LibSWBF2/LibSWBF2#30]
Reverse Engineer the last frontier of missing assets and implement respective functionaility into the library, such that we can query the PCM data of every requested sound. We also need to think about a possibility to stream the data, such that we don't need to load an entire music track into memory to play it back.

Sound chunks: `/LibSWBF2/Chunks/LVL/sound/`

**Comment by phantom567459** [comment]
Do you need any more documentation of the format itself?  I can help with the documentation and identification but C++ is not my strong suit.

**Comment by Ben1138** [comment]
Sure thing, any help is welcome! I was actually under the impression that your SoundFMVextractor just extracts .bnk files. PM me on Discord.

**Comment by WHSnyder** [comment]
Effects working and tested in Unity (#37).  Next PR will be for streams, the `Sound` and `SoundStream` wrappers will change a lot.  `Level`s will also be able to retain their streams after reading all chunks.
