### ISSUE TITLE
Map Animations (LibSWBF2)

### ISSUE THREAD

**Issue by Ben1138** [LibSWBF2/LibSWBF2#31]
In ZE, you can define Animations to move objects around. These can be triggered in Lua via PlayAnimation, PauseAnimation and RewindAnimation. One example of this would be the bridge on Mustafar, moving down when the control panels are destroyed and moving up again when repaired.

![grafik](https://user-images.githubusercontent.com/8263806/150681076-4d0463c1-68a2-41a8-9f0e-0ee9d5cfe7ee.png)

You can start within these files:
* LibSWBF2/Chunks/LVL/wrld/anmg.cpp
* LibSWBF2/Chunks/LVL/wrld/anim.cpp

Implement proper chunk types for INFO, POSK and ROTK (they are currently just RawData and STR chunks).
Also implement the respective wrapper classes + the C# wrapping.

**Comment by WHSnyder** [comment]
#34

**Comment by WHSnyder** [comment]
Done in #34
